# Generated by Django 4.0.1 on 2022-01-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_stuff', '0002_alter_student_ph_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=':(fohgjare', max_length=256),
            preserve_default=False,
        ),
    ]
