# Generated by Django 4.0.2 on 2022-02-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_stuff', '0004_student_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(default='', max_length=128),
        ),
    ]
