# Generated by Django 4.0.2 on 2022-02-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_stuff', '0005_alter_student_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='house_num',
            field=models.CharField(default='', max_length=128),
        ),
    ]
