# Generated by Django 4.0.2 on 2022-02-17 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_stuff', '0006_alter_student_house_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ph_num',
            field=models.CharField(default='', max_length=32, validators=[django.core.validators.RegexValidator('^\\d{1,11}$')]),
        ),
    ]
