# Generated by Django 3.2.9 on 2021-12-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('index', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='topic_pics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.topic')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'topic_tag',
                'verbose_name_plural': 'topic_tags',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TopicTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.topictag')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.topic')),
            ],
            options={
                'verbose_name': 'topictag',
                'verbose_name_plural': 'topictags',
                'ordering': ['id'],
            },
        ),
    ]
