# Generated by Django 3.2.9 on 2021-12-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.JSONField(),
        ),
    ]
