# Generated by Django 4.0.1 on 2022-01-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_stuff', '0002_alter_role_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='deletable',
            field=models.BooleanField(default=False),
        ),
    ]
