# Generated by Django 3.2.9 on 2021-12-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_stuff', '0004_auto_20211201_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdepartment',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
