# Generated by Django 3.2.9 on 2021-12-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_stuff', '0005_staffdepartment_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default='..'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='cover_pic',
            field=models.ImageField(default='cover_pics/default.jpg', upload_to='cover_pics'),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(default='unapproved', max_length=128),
        ),
    ]
