# Generated by Django 3.2.9 on 2021-12-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_stuff', '0006_auto_20211224_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
