# Generated by Django 3.2.9 on 2022-01-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_stuff', '0007_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='card_pic',
            field=models.ImageField(default='card_pics/default.jpg', upload_to='card_pics'),
        ),
    ]
