# Generated by Django 3.2.9 on 2022-01-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_stuff', '0009_staff_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='shorthand',
            field=models.CharField(default='DEF', max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffdepartment',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
