# Generated by Django 3.2.9 on 2022-01-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role_stuff', '0001_initial'),
        ('staff_stuff', '0010_auto_20220109_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='role_stuff.role'),
        ),
        migrations.AddField(
            model_name='staffdepartment',
            name='job',
            field=models.CharField(default='member', max_length=256),
        ),
    ]
