# Generated by Django 4.0.1 on 2022-01-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_stuff', '0013_staff_city_staff_country_staff_house_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(default='in progress', max_length=128),
        ),
    ]
