# Generated by Django 4.0.1 on 2022-01-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_stuff', '0014_alter_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gmail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
