# Generated by Django 4.0.1 on 2022-01-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_stuff', '0015_staff_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='deletable',
            field=models.BooleanField(default=True),
        ),
    ]
