# Generated by Django 4.0.1 on 2022-02-01 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role_stuff', '0003_role_deletable'),
        ('staff_stuff', '0016_tag_deletable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='role_stuff.role'),
        ),
    ]
