# Generated by Django 4.0.2 on 2022-02-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_stuff', '0018_job_alter_staffdepartment_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdepartment',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='stafftag',
            name='pos',
        ),
        migrations.AlterField(
            model_name='staff',
            name='region',
            field=models.CharField(default='', max_length=128),
        ),
    ]
