# Generated by Django 4.0.2 on 2022-02-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_stuff', '0019_remove_staffdepartment_pos_remove_stafftag_pos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='channel_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='ms_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
