# Generated by Django 3.2.9 on 2021-12-04 04:06

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(default='Description...')),
                ('meeting_id', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{1,11}$ ')])),
                ('viber_group', models.CharField(default='https://', max_length=256)),
                ('classcode', models.CharField(default='#code', max_length=8)),
                ('valid_from', models.DateField(default=datetime.date(2000, 1, 1))),
                ('valid_to', models.DateField(default=datetime.date(2000, 1, 1))),
                ('status', models.CharField(default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predecessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_stuff.work')),
            ],
            options={
                'verbose_name': 'work',
                'verbose_name_plural': 'works',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_stuff.work')),
            ],
            options={
                'verbose_name': 'staffwork relation',
                'verbose_name_plural': 'staffwork relations',
                'ordering': ['-id'],
            },
        ),
    ]
