# Generated by Django 3.2.9 on 2021-12-24 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_stuff', '0003_auto_20211206_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='valid_to',
            field=models.DateField(default=datetime.date(2000, 12, 1)),
        ),
    ]
