# Generated by Django 3.2.9 on 2021-12-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_stuff', '0005_auto_20211224_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='classcode',
            new_name='class_code',
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
