# Generated by Django 4.0.1 on 2022-01-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_stuff', '0007_auto_20220109_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='ms_id',
            field=models.CharField(default='', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
