# Generated by Django 4.0.1 on 2022-01-25 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_stuff', '0008_work_ms_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='class_code',
        ),
        migrations.RemoveField(
            model_name='work',
            name='meeting_id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='viber_group',
        ),
        migrations.AddField(
            model_name='work',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
