# Generated by Django 4.0.1 on 2022-01-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_stuff', '0009_remove_work_class_code_remove_work_meeting_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='event_id',
            field=models.CharField(default='sjgosnhgwvsvnurghs', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
