# Generated by Django 4.0.1 on 2022-01-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_stuff', '0010_session_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='channel_id',
            field=models.CharField(default='sgsgsg', max_length=256),
            preserve_default=False,
        ),
    ]
