# Generated by Django 4.0.1 on 2022-01-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_stuff', '0011_work_channel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='organizer',
        ),
    ]
