# Generated by Django 4.0.1 on 2022-01-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_stuff', '0012_remove_work_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='event_id',
        ),
    ]
